io.rsocket.routing.client:
  route-id: 00000000-0000-0000-0000-000000000003
  service-name: pong
  tags:
    INSTANCE_NAME: pong3
  brokers:
    - tcp:
        host: localhost
        port: 8002

logging:
  level:
    io.rsocket.routing.client: DEBUG
---
spring.config.activate.on-profile: server
pong:
  client: false

---
spring.config.activate.on-profile: pong4

io.rsocket.routing.client:
  route-id: 00000000-0000-0000-0000-000000000004
  service-name: pong
  tags:
    INSTANCE_NAME: pong4

---
spring.config.activate.on-profile: broker2

io.rsocket.routing.client:
  brokers:
    - tcp:
        host: localhost
        port: 8003

---
spring.config.activate.on-profile: broker21

io.rsocket.routing.client:
  route-id: 00000000-0000-0000-0000-000000000021
  service-name: pong
  tags:
    INSTANCE_NAME: pong21
  brokers:
    - tcp:
        host: localhost
        port: 8003
