io.rsocket.routing.client:
  route-id: 00000000-0000-0000-0000-000000000003
  service-name: service
  tags:
    INSTANCE_NAME: service3
  brokers:
    - tcp:
        host: localhost
        port: 8002

logging:
  level:
    io.rsocket.routing.client: DEBUG
